"""renders a whole ros 2 package around one mission plan. no ros imports so
it tests anywhere.

the forge exists so a primed mission can outlive the mission host: instead of
an in-process executor the plan gets its own package, its own `ros2 run` entry
point and its own supervisord program, which means it survives a host restart
and shows up in `supervisorctl status` like any other process.

the generated node is deliberately thin. it embeds the plan and hands it
straight to mission_node.run_executor, so a forged node and a host child fly
identical code - the only difference is who owns the process.

templates substitute a __FORGE_NAME__/__FORGE_PLAN__ sentinel rather than
str.format or Template: the rendered files are full of braces and $vars of
their own.
"""

import json
import sys
from collections.abc import Iterable
from typing import Any

from .mission_plan import NAME_PATTERN, NAME_RE, MissionError

MAINTAINER = "Tim Nguyen"
MAINTAINER_EMAIL = "tim.h.nguyen06@gmail.com"

# names that would collide with a supervisord program, a package this one
# imports, or a ros node the stack already owns. forging one would shadow a
# running process or make `supervisorctl <name>` ambiguous.
_RESERVED = {
    "px4",
    "px4_msgs",
    "px4-sim-params",
    "gz-server",
    "gz-gui",
    "gz_server",
    "gz_gui",
    "xrce-agent",
    "xrce_agent",
    "dds-agent",
    "dds_agent",
    "api",
    "web",
    "vnc",
    "novnc",
    "xvfb",
    "x11vnc",
    "qgc",
    "qgc-link",
    "qgc_link",
    "mission",
    "mission_host",
    "mission_node",
    "teleop",
    "offboard_demo",
    "offboard-demo",
    "node-forge",
    "node_forge",
    "forge",
    "rclpy",
    "std_msgs",
    "geometry_msgs",
    "supervisor",
    "setuptools",
    "resource",
    "test",
}

# a forged package lands on PYTHONPATH ahead of the stdlib, so a package
# named `json` or `socket` would break every python process in the container
RESERVED_NAMES = frozenset(_RESERVED | set(sys.stdlib_module_names))


def validate_forge_name(
    name: Any, reserved: Iterable[str] = RESERVED_NAMES
) -> str:
    """the contract's name pattern plus the names the container already owns."""
    if not isinstance(name, str) or not NAME_RE.fullmatch(name):
        raise MissionError(f"name must match {NAME_PATTERN}")
    if name in set(reserved):
        raise MissionError(f"name {name!r} is reserved by the stack; pick another")
    return name


_PACKAGE_XML = """<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>__FORGE_NAME__</name>
  <version>0.1.0</version>
  <description>Forged puffin mission node: flies the plan embedded in node.py.</description>
  <maintainer email="__FORGE_EMAIL__">__FORGE_MAINTAINER__</maintainer>
  <license>MIT</license>

  <exec_depend>offboard_demo</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>px4_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
"""

_SETUP_PY = '''from setuptools import setup

# generated by offboard_demo.forge - re-forging __FORGE_NAME__ overwrites this
package_name = "__FORGE_NAME__"

setup(
    name=package_name,
    version="0.1.0",
    packages=[package_name],
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
        ("share/" + package_name, ["package.xml"]),
    ],
    install_requires=["setuptools"],
    zip_safe=True,
    description="Forged puffin mission node.",
    license="MIT",
    entry_points={
        "console_scripts": [
            "__FORGE_NAME__ = __FORGE_NAME__.node:main",
        ],
    },
)
'''

# ros2 run looks for the console script in lib/<package>, not bin
_SETUP_CFG = """[develop]
script_dir=$base/lib/__FORGE_NAME__
[install]
install_scripts=$base/lib/__FORGE_NAME__
"""

_NODE_PY = '''"""forged mission node: __FORGE_NAME__.

generated by offboard_demo.forge from the plan below - re-forging this name
overwrites the file, so edit the mission, not this. the flight logic stays in
offboard_demo: this node is only a name, a plan and a process.

one-shot: run_executor flies the plan once when activated, then hands px4 back
to AUTO.LOITER and exits 0. `supervisorctl start __FORGE_NAME__` replays it.
"""

from offboard_demo.mission_node import run_executor
from offboard_demo.mission_plan import parse_mission

NAME = "__FORGE_NAME__"

# the MissionRequest this node was forged from, verbatim
PLAN_JSON = """__FORGE_PLAN__"""


def main() -> None:
    run_executor(NAME, parse_mission(PLAN_JSON))


if __name__ == "__main__":
    main()
'''

# priority 48: after the mission host (47), before the forge watcher (49) that
# writes this block - a forged node is up before the watcher reports done.
_SUPERVISORD_CONF = """[program:__FORGE_NAME__]
; forged mission node. boots to inactive like every other flight node, so the
; api only ever sends activate; the plan is baked into the package.
; a completed mission exits 0, so 0 is an expected exit code and autorestart
; only covers crashes - the node parks at EXITED instead of respawning into
; the same flight, and `supervisorctl start __FORGE_NAME__` replays it.
command = bash -c "source /ros_ws/install/setup.bash && ros2 run __FORGE_NAME__ __FORGE_NAME__"
priority = 48
autostart = true
autorestart = unexpected
exitcodes = 0
"""


def _fill(template: str, name: str, plan_json: str = "") -> str:
    return (
        template.replace("__FORGE_NAME__", name)
        .replace("__FORGE_PLAN__", plan_json)
        .replace("__FORGE_EMAIL__", MAINTAINER_EMAIL)
        .replace("__FORGE_MAINTAINER__", MAINTAINER)
    )


def render_package(plan: dict[str, Any]) -> dict[str, str]:
    """file path (relative to the package root) -> content, ready to write."""
    name = validate_forge_name(plan.get("name"))
    plan_json = json.dumps(plan, indent=2, sort_keys=True)
    # every value in a parsed plan is a number, a bool or the validated name,
    # so this can only trip if the plan shape grows a free-text field
    if '"""' in plan_json or "\\" in plan_json:
        raise MissionError("plan json cannot be embedded verbatim")
    return {
        "package.xml": _fill(_PACKAGE_XML, name),
        "setup.py": _fill(_SETUP_PY, name),
        "setup.cfg": _fill(_SETUP_CFG, name),
        f"resource/{name}": "",
        f"{name}/__init__.py": "",
        f"{name}/node.py": _fill(_NODE_PY, name, plan_json),
    }


def render_supervisord_conf(name: str) -> str:
    """the [program:<name>] block supervisord picks up from its drop-in dir."""
    return _fill(_SUPERVISORD_CONF, validate_forge_name(name))
